# write a pod to test the volume
apiVersion: v1
kind: Pod
metadata:
#set name as the JOBNAME
  name: job
spec:
  containers:
  - name: test-shell
    image: temp.sh
    command:
      - "{echo_string: hello world}"
      - "{_process_exporter_port: 1912}"
      - "{_prom_server: jeng-yuantsai@72.84.73.170}"
      - "{_user_image: jlabtsai/stress:p4}"
    args:
      - "{env1: val1}"
      - "{env2: val2}"
      - "{a:v1}"
      - "{b:v2}"
      - "{c:12343}"
    resources:
      limits: 
        cpu: 1 #upper limit
        # memory: 500Mi
      requests:
        cpu: 1 #lower limit
        # memory: 200Mi
 
# dont use control-plane node
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"