---
kind: ConfigMap
apiVersion: v1
metadata:
  name: stress
  namespace: default
data:
  stress.sh: |
    echo "shifter --image=docker:jlabtsai/stress:p1 --entrypoint" > $HOME/hostpipe/vk-cmd
     
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: cow
  namespace: default
data:
  cow.sh: |
    echo 'shifter --image=godlovedc/lolcow:latest --entrypoint > $HOME/cow.out' > $HOME/hostpipe/vk-cmd
---

apiVersion: v1
kind: Pod
metadata:
  name: 2-job
spec:
  containers:
  - name: stress
    image: docker:jlabtsai/stress:p1
    command: ["/bin/bash"]
    volumeMounts:
    - name: stress-job
      mountPath: /stress

  - name: cow
    image: godlovedc/lolcow:latest
    command: ["/bin/bash"]
    volumeMounts:
    - name: cow-job
      mountPath: /cow


  volumes:
    - name: stress-job
      configMap:
        name: stress
    - name: cow-job
      configMap:
        name: cow
        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"


---
