kind: ConfigMap
apiVersion: v1
metadata:
  name: u1-j1
  namespace: default
data:
  u1-j1.sh: |
    #!/bin/bash
    echo "u1-j1" > ~/u1-j1.txt
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: u1-j2
  namespace: default
data :
  u1-j2.sh: |
    #!/bin/bash
    echo "u1-j2" > ~/u1-j2.txt


---
kind: ConfigMap
apiVersion: v1
metadata:
  name: stress
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    echo "shifter --image=docker:jlabtsai/stress:p1 --entrypoint" > $HOME/hostpipe/vk-cmd
     
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: cow
  namespace: default
data:
  cow.sh: |
    #!/bin/bash
    echo 'shifter --image=godlovedc/lolcow:latest --entrypoint > $HOME/cow.out' > $HOME/hostpipe/vk-cmd
---

apiVersion: v1
kind: Pod
metadata:
  name: cow
spec:
  containers:
  - name: u1
    image: u1
    command: [""]
    volumeMounts:
    - name: stress-job
      # read from configmap
      mountPath: stress-job
    # - name: cow-job
      # mountPath: cow-job # path is auto generated by vk, the rule is: $HOME/podname/configmapname/volumename.

  # - name: u2
  #   image: u2
  #   command: [""]
  #   volumeMounts:
  #   - name: u2-j1
  #     mountPath: u2-j1 # path is auto generated by vk, the rule is: $HOME/podname/configmapname/volumename.

  volumes:
    - name: stress-job
      configMap:
        name: stress
    - name: cow-job
      configMap:
        name: cow
    
    # - name: u1-j2
    #   configMap:
    #     name: u1-j2

    # - name: u2-j1
    #   configMap:
    #     name:  u2-j1

        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"


---
